    # Generated by Custom Compiler
    # Target: x86-64 Assembly (AT&T syntax)

    # Runtime support functions
.data
.LC0:
    .string "%d\n"
.LC1:
    .string "%f\n"

.text
    # ==========================================
    # compute
    # ==========================================
    # Function prologue
    compute:
    pushq %rbp
    movq %rsp, %rbp
    # Reserve space for local variables
    subq $64, %rsp
    # Assignment
    movq $10, %rax
    movq %rax, -8(%rbp)
    # Assignment
    movq $5, %rax
    movq %rax, -8(%rbp)
    # Assignment
    movq -8(%rbp), %rax
    addq %r10, %rax
    movq %rax, -8(%rbp)
    # Return statement
    movq -8(%rbp), %rax
    # Function epilogue
    movq %rbp, %rsp
    popq %rbp
    ret
    movq $0, %rax
    # Function epilogue
    movq %rbp, %rsp
    popq %rbp
    ret

