    # Generated by Custom Compiler
    # Target: x86-64 Assembly (AT&T syntax)

    # Runtime support functions
.data
.LC0:
    .string "%d\n"
.LC1:
    .string "%f\n"

.text
    # ==========================================
    # testDuplicates
    # ==========================================
    # Function prologue
    testDuplicates:
    pushq %rbp
    movq %rsp, %rbp
    # Reserve space for local variables
    subq $64, %rsp
    movq $0, %rax
    # Function epilogue
    movq %rbp, %rsp
    popq %rbp
    ret

